project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "floating"
    search: false
    contents:
      - section: "Basis Oekraïense uitdrukkingen en woordenschat"
        contents:
          # - index.qmd
          - ch02_mc.qmd
          - ch02_mc_exam.qmd
          - ch02_input_exam.qmd
      - section: "Zelfstandige Naamwoorden"
        contents:  
          - ch03_secties.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



