project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "floating"
    search: false
    contents:
      - section: "Chapter 2"
        contents:
          - index.qmd
          - quiz.qmd
          - quiz_input.qmd
          - ch02_mc.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



